spring:
  application:
    name: notification-service
  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    stream:
      bindings:
        notificationEventSupplier-in-0:
          destionation: notification-events

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 0
