spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leoluzh/shopping-microservices-with-spring-cloud-config
          username:
          password:
          clone-on-start: true

server:
  port: 8888
